name: ANKIT PATIL PORTFOLIO

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Push Next.js Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build # This will now also handle the export to the 'out' directory

      # REMOVE THIS STEP - IT'S NO LONGER NEEDED AND CAUSES THE ERROR
      # - name: Export static site
      #   run: npm run export # only if you're using `next export`

      - name: Push to build branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: out # This is correct, as `next build` with `output: 'export'` will place files here
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"